language: ruby
cache: bundler
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
script:
  - bundle exec rake
notifications:
  email:
    - diego.domingues16@gmail.com
rvm:
  - 2.2.2
addons:
  code_climate:
    repo_token: 8c6bdfbec7879434fc4104044e2f9dfb0c7ffeb4b04d99f21256cf4e432a7617